### PR TITLE
Unique ptr

### PR DESCRIPTION
**Pull request by trenata**

### CODE REVIEW

**Review by CristianIonutIonescu — COMMENTED** [review]
there are 2 things that are missing from your unique ptr implementation:
- your unique_ptr is copy constructible and it shouldn't 
- missing deleter from the class

**Review by CristianIonutIonescu — CHANGES_REQUESTED** [review]
issues described in previous review have not been solved

**Comment by trenata** [comment]
I accidentally pushed that commit before realising I already got a PR review, and after I didn't have time to work on it. I'm sorry. Now I solved the issues you described.

**Review by CristianIonutIonescu — APPROVED** [review]
great job!!
PS: no need to be sorry, we all make mistakes

**Pull request merged**
